# render.yaml
services:
  - type: cron
    name: price-scraper
    runtime: docker
    schedule: "0 0 * * *"
    dockerfilePath: ./Dockerfile
    dockerCommand: "python src/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: BLUPAX_SESSION_ID
        sync: false
      - key: PARMED_USERNAME
        sync: false
      - key: PARMED_PASSWORD
        sync: false
      - key: OX_USERNAME
        sync: false
      - key: OX_PASSWORD
        sync: false
      - key: OX_PROXY_SERVER_ADDRESS
        sync: false

