-- Create wholesaler-tracking schema and tables for scrapers

CREATE SCHEMA IF NOT EXISTS wholesaler_tracking;

CREATE TABLE IF NOT EXISTS wholesaler_tracking.parmed (
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cin TEXT,
    itemId TEXT,
    sku TEXT,
    description TEXT,
    ndc TEXT,
    manufacturer TEXT,
    strength TEXT,
    packQuantity TEXT,
    color TEXT,
    unitOfSale TEXT,
    form TEXT,
    specialHandling TEXT,
    labelSize TEXT,
    brandName TEXT,
    caseQty TEXT,
    isCSOS BOOLEAN,
    gcn TEXT,
    temperature TEXT,
    isBlocked BOOLEAN,
    hin TEXT,
    price NUMERIC,
    allocatedQuantity INTEGER,
    gcnCount INTEGER,
    isLowestPriceFlag BOOLEAN,
    onOrder BOOLEAN,
    isWatchListItem BOOLEAN,
    isFavListItem BOOLEAN,
    unavailabilityReason TEXT,
    ndc2 TEXT,
    isSubscriable BOOLEAN,
    isSubscribed BOOLEAN,
    isNegotiable BOOLEAN,
    isNegotiated BOOLEAN,
    isNegotiatePending BOOLEAN,
    rtrnable_flg BOOLEAN,
    remsFlag BOOLEAN,
    gtin TEXT,
    shape TEXT,
    he TEXT
);

CREATE TABLE IF NOT EXISTS wholesaler_tracking.blupax (
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id TEXT,
    wac NUMERIC,
    awp NUMERIC,
    unit_price NUMERIC,
    price NUMERIC,
    website_url TEXT,
    ndc_formatted TEXT,
    item_number TEXT,
    display_item_number TEXT,
    description TEXT,
    product_size TEXT,
    manufacturer_name TEXT,
    brand TEXT,
    strength TEXT,
    is_available BOOLEAN,
    short_dated BOOLEAN,
    manufacturer_short_name TEXT,
    expiration_date TIMESTAMPTZ,
    extension_date TIMESTAMPTZ,
    quantity INTEGER,
    eta TIMESTAMPTZ,
    is_eta_delayed BOOLEAN,
    active BOOLEAN,
    is_short_dated BOOLEAN,
    cloudflare_image_url TEXT,
    branding_type TEXT,
    generic_name TEXT,
    can_add_to_cart BOOLEAN,
    create_date TIMESTAMPTZ,
    display_name TEXT,
    lot_number TEXT,
    dosage_form TEXT,
    item_group_filter TEXT,
    availability_status TEXT,
    show_short_dated_label BOOLEAN,
    display_dea_class TEXT,
    hide_dea_icon BOOLEAN,
    restricted_by_dea BOOLEAN,
    last_ordered_date TIMESTAMPTZ,
    is_wishlisted BOOLEAN,
    is_gpi_restriction BOOLEAN
);